version: '3.8'

services:
  node-app:
    build:
      context: ./server
    ports:
      - 3000:3000
    networks:
      - myNetwork
 
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - myNetwork
    depends_on:
      - node-app

networks:
  myNetwork: